name: Stock Scanner Bot

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  run-bot:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10' # Phải để trong dấu nháy đơn để ép dùng đúng 3.10

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install setuptools==69.5.1
          # Cài đặt các thư viện cốt lõi với phiên bản cụ thể
          pip install pandas==2.0.3 pyTelegramBotAPI vnstock
          # Sử dụng link cài trực tiếp không qua build để tránh lỗi pkg_resources
          pip install https://github.com/twopirllc/pandas-ta/archive/refs/heads/master.zip

      - name: Execute Scanner
        env:
          TELEGRAM_TOKEN: ${{'8625301702:AAHLOJgz_fIkfA6WpU7Sr60KjRIzc7nmHR4'}}
          TELEGRAM_CHAT_ID: ${{'1736294695'}}
        run: python bot.py
